import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import AuthProvider from '@/providers/AuthProvider';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900', // Correct variable font weight range
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900', // Correct variable font weight range
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex justify-center`}
      >
        <ToastContainer />
        <div className='hidden min-[320px]:block w-[500px] max-w-screen-md min-h-screen'>
          <AuthProvider>
            {children}
          </AuthProvider>
        </div>
        <div className='p-10 min-[320px]:hidden'>
          <h1 className='font-bold text-4xl'>Opsie!</h1>
          <span className='font-light text-md'>
            This App Not Support on Your Device Screen
          </span>
        </div>
      </body>
    </html>
  );
}
